[PHP]
extension_dir = "C:\Windows\php-8.5.3\ext"
extension=pdo_sqlite
extension=sqlite3
extension=mbstring
extension=curl
extension=openssl
extension=fileinfo
extension=gd

file_uploads = On
upload_max_filesize = 100M
post_max_size = 100M

display_errors = Off
display_startup_errors = Off
error_reporting = E_ALL & ~E_DEPRECATED
